/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MundoRouteImport } from './routes/mundo'
import { Route as MisteriosRouteImport } from './routes/misterios'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as HabitantesRouteImport } from './routes/habitantes'
import { Route as IndexRouteImport } from './routes/index'

const MundoRoute = MundoRouteImport.update({
  id: '/mundo',
  path: '/mundo',
  getParentRoute: () => rootRouteImport,
} as any)
const MisteriosRoute = MisteriosRouteImport.update({
  id: '/misterios',
  path: '/misterios',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitantesRoute = HabitantesRouteImport.update({
  id: '/habitantes',
  path: '/habitantes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habitantes': typeof HabitantesRoute
  '/inicio': typeof InicioRoute
  '/misterios': typeof MisteriosRoute
  '/mundo': typeof MundoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habitantes': typeof HabitantesRoute
  '/inicio': typeof InicioRoute
  '/misterios': typeof MisteriosRoute
  '/mundo': typeof MundoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/habitantes': typeof HabitantesRoute
  '/inicio': typeof InicioRoute
  '/misterios': typeof MisteriosRoute
  '/mundo': typeof MundoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/habitantes' | '/inicio' | '/misterios' | '/mundo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/habitantes' | '/inicio' | '/misterios' | '/mundo'
  id: '__root__' | '/' | '/habitantes' | '/inicio' | '/misterios' | '/mundo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabitantesRoute: typeof HabitantesRoute
  InicioRoute: typeof InicioRoute
  MisteriosRoute: typeof MisteriosRoute
  MundoRoute: typeof MundoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mundo': {
      id: '/mundo'
      path: '/mundo'
      fullPath: '/mundo'
      preLoaderRoute: typeof MundoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misterios': {
      id: '/misterios'
      path: '/misterios'
      fullPath: '/misterios'
      preLoaderRoute: typeof MisteriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitantes': {
      id: '/habitantes'
      path: '/habitantes'
      fullPath: '/habitantes'
      preLoaderRoute: typeof HabitantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabitantesRoute: HabitantesRoute,
  InicioRoute: InicioRoute,
  MisteriosRoute: MisteriosRoute,
  MundoRoute: MundoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
